I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 173, in script call
    call survey
  File "game/script.rpy", line 173, in script call
    call survey
ScriptError: could not find label 'survey'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 173, in script call
    call survey
  File "C:\Games\renpy-8.1.3-sdk\renpy\ast.py", line 1725, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 173, in script call
    call survey
  File "C:\Games\renpy-8.1.3-sdk\renpy\script.py", line 1013, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'survey'.

Windows-10-10.0.22621 AMD64
Ren'Py 8.1.3.23091805
What remains of Ken 1.0
Sun Nov  5 13:41:25 2023
